import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Navigation from "./components/Navigation/Navigation";
import { Providers } from "./store/provider";

const montserrat = Montserrat({
  subsets: ["cyrillic", "latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dataTab = [
  {
    name: 'Add',
    location: '/add'
  },
  {
    name: 'Search',
    location: '/search/all'
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <main className="vh-100">
            <section className="container py-5 h-100">
              <div className="row d-flex justify-content-center align-items-center h-100">
                <div className="col col-xl-10">
                  <div className="card">
                    <div className="card-body p-5">
                    <Navigation data={dataTab}/>
                      {children}
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
